### ISSUE TITLE
熹微README.md

### ISSUE THREAD

**Issue by LeoBuscaglia** [a-jingchao/dim-star#1]

**Comment by OHUHO** [comment]
What do you mean?

**Comment by LeoBuscaglia** [comment]
> What do you mean?

I'm so new bro I'm trying to learn, sorry

**Comment by OHUHO** [comment]
No, no, you may have misunderstood me, I mean what kind of description do you mean?

**Comment by OHUHO** [comment]
What kind of description do I need to provide?

**Comment by LeoBuscaglia** [comment]
> What kind of description do I need to provide?

I came to watch a movie but I couldn't understand it so I couldn't get it to work

**Comment by OHUHO** [comment]
Did you get an error message when you were building the project?

**Comment by LeoBuscaglia** [comment]
> Did you get an error message when you were building the project?

The problem is not you my friend, I don't even know how to operate

**Comment by LeoBuscaglia** [comment]
> Did you get an error message when you were building the project?

I'm very new and I don't know how to do it I guess I need to learn this

**Comment by OHUHO** [comment]
May I ask, can you understand the Chinese on the readme document? My English is still learning. I think you can understand it better if you change it to English documents.

**Comment by LeoBuscaglia** [comment]
> May I ask, can you understand the Chinese on the readme document? My English is still learning. I think you can understand it better if you change it to English documents.

I will try to translate

**Comment by OHUHO** [comment]
come on! bro
